import Navbar from "@/components/Navbar";
import "./globals.css";
import { Open_Sans } from "next/font/google";
import Footer from "@/components/Footer";
import AuthContext from "@/context/AuthContext";
import { SWRConfigContext } from "@/context/SWRConfigContext";

const sans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={sans.className}>
      <body>
        <AuthContext>
          <header className="sticky top-0 z-10">
            <Navbar />
          </header>
          <main className="min-h-screen">
            <SWRConfigContext>{children}</SWRConfigContext>
          </main>
          <footer>
            <Footer />
          </footer>
        </AuthContext>
        <div id="portal" />
      </body>
    </html>
  );
}
